compaign:
    resource: "@CompaignBundle/Resources/config/routing.yml"
    prefix:   /cmp

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
compaign_space:
    path:     /display
    defaults: { _controller: CompaignBundle:Compaign:Display }
prop_space:
    path:     /display Proposition
    defaults: { _controller: CompaignBundle:Proposition:DisplayProp }
compaign_spacefront:
    path:     /display Front
    defaults: { _controller: CompaignBundle:Compaign:DisplayFront }
compaign_signle:
    path:     /display Signle/{id}
    defaults: { _controller: CompaignBundle:Compaign:DisplaySignle }
donate:
    path:     /Donating/{idc}
    defaults: { _controller: CompaignBundle:Compaign:Donate }