news_homepage:
    path:     /
    defaults: { _controller: NewsBundle:News:index }
news_newsf:
    path:     /Front/newsf
    defaults: { _controller: NewsBundle:News:newsf }

news_affichnews:
    path:     /affichnews
    defaults: { _controller: NewsBundle:News:affichnews }

news_allnews:
    path:     /allnews/{m}
    defaults: { _controller: NewsBundle:News:allnews }

news_affichcat:
    path:     /affichcat
    defaults: { _controller: NewsBundle:News:affichcat }

news_affichnewsd:
    path:     /affichnewsd/{id}
    defaults: { _controller: NewsBundle:News:affichnewsd }

news_pdfnewsd:
    path:     /pdfnewsd/{id}
    defaults: { _controller: NewsBundle:News:pdfnewsd }

news_deletenews:
    path:     /deletenews/{id}
    defaults: { _controller: NewsBundle:News:deletenews }

news_deletecat:
    path:     /deletecat/{id}
    defaults: { _controller: NewsBundle:News:deletecat }

news_modifynews:
    path:     /modifynews/{id}
    defaults: { _controller: NewsBundle:News:modifynews }

news_ajoutnews:
    path:     /ajoutnews
    defaults: { _controller: NewsBundle:News:ajoutnews }

news_modifycat:
    path:     /modifycat/{id}
    defaults: { _controller: NewsBundle:News:modifycat }

news_ajoutcat:
    path:     /ajoutcat
    defaults: { _controller: NewsBundle:News:ajoutcat }

news_statnews:
    path:     /statnews
    defaults: { _controller: NewsBundle:News:statnews }
