event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /evt
event_space:
    path:     /display
    defaults: { _controller: EventBundle:Event:Display }
gallery_space:
    path:     /displayG
    defaults: { _controller: EventBundle:Event:DisplayG }
All_EventP:
    path:     /displayAll
    defaults: { _controller: EventBundle:Event:DisplayFrontAll }
All_EventS:
    path:     /displayAllS
    defaults: { _controller: EventBundle:Event:DisplayFrontAllS }
All_EventG:
    path:     /displayAllG
    defaults: { _controller: EventBundle:Event:DisplayFrontAllG }
sponsor:
    path:     /displayS
    defaults: { _controller: EventBundle:Event:DisplayAllS }
partici:
    path:     /displayP
    defaults: { _controller: EventBundle:Event:DisplayAllP }
stat:
    path:     /displayStat
    defaults: { _controller: EventBundle:Event:DisplayStat}
indexFront:
    path:     /index
    defaults: { _controller: AppBundle:Default:indexFront }
dashboard:
    path:     /indexB
    defaults: { _controller: AppBundle:Default:Dashboard }
app:
    resource: '@AppBundle/Controller/'
    type: annotation
# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
