Delivery:
    type: entity
    table: delivery
    id:
        idde:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: IdDe
            generator:
                strategy: IDENTITY
    fields:
        iddman:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: idDman
        dated:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: DateD
        item:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
    lifecycleCallbacks: {  }
