<?php

namespace AppBundle\Repository;

/**
 * montaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class montaRepository extends \Doctrine\ORM\EntityRepository
{
}
