event_homepage:
  path:     /
  defaults: { _controller: EventBundle:Default:index }
event_exp:
  path:     /index
  defaults: { _controller: EventBundle:Event:index }
event_delete:
  path:     /delete/{id}
  defaults: { _controller: EventBundle:Event:delete }
event_create:
  path:     /create
  defaults: { _controller: EventBundle:Event:create }
event_update:
  path:     /update/{id}
  defaults: { _controller: EventBundle:Event:update }
gallery_create:
  path:     /createG
  defaults: { _controller: EventBundle:Event:createG }
img_display:
  path:     /displayImg/{id}
  defaults: { _controller: EventBundle:Event:DisplayImg }
img_delete:
  path:     /deleteG/{id}
  defaults: { _controller: EventBundle:Event:deleteImg }
img_update:
  path:     /updateG/{id}
  defaults: { _controller: EventBundle:Event:updateImg }
event_singleP:
  path:     /single/{id}
  defaults: { _controller: EventBundle:Event:DisplaySingleP }
delete_P:
  path:     /DeleteP/{id}
  defaults: { _controller: EventBundle:Event:DeleteParticipation }
Add_P:
  path:     /AddP/{id}
  defaults: { _controller: EventBundle:Event:AddParticipation }
Print_pdf:
  path:     /invit/{id}
  defaults: { _controller: EventBundle:Event:PrintPdf }
event_singleS:
  path:     /singleS/{id}
  defaults: { _controller: EventBundle:Event:DisplaySingleS }
Add_S:
  path:     /AddS/{id}
  defaults: { _controller: EventBundle:Event:AddSponsor }
sponsor_display:
  path:     /displaySponsor/{id}
  defaults: { _controller: EventBundle:Event:DisplaySponsor }
partici_display:
  path:     /displayPartici/{id}
  defaults: { _controller: EventBundle:Event:DisplayPartici }