<?php

namespace AppBundle\Repository;

/**
 * OrdeerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdeerRepository extends \Doctrine\ORM\EntityRepository
{
}
