Categorie:
    type: entity
    table: categorie
    uniqueConstraints:
        nomcat:
            columns:
                - nomcat
    id:
        idc:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nomcat:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
    lifecycleCallbacks: {  }
