Sponsorship:
    type: entity
    table: sponsorship
    id:
        idsp:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idSp
            generator:
                strategy: IDENTITY
    fields:
        idSponsor:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_sponsor
        idEvt:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_evt
        logo:
            type: string
            nullable: false
            length: 85
            options:
                fixed: false
        givenSponsor:
            type: float
            nullable: false
            precision: 10
            scale: 0
            column: given_sponsor
        dateSponsor:
            type: date
            nullable: false
            column: date_sponsor
    lifecycleCallbacks: {  }
