blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:index }
blog_login:
    path:     /loginnn
    defaults: { _controller: BlogBundle:Blog:showLogin }
blog_signin:
    path:     /sign
    defaults: { _controller: BlogBundle:User:signin }
blog_show:
    path:     /showB
    defaults: { _controller: BlogBundle:Blog:show }
blog_createPosts:
    path:     /createP
    defaults: { _controller: BlogBundle:Blog:createP }
blog_deletePost:
    path:     /delete/{id}
    defaults: { _controller: BlogBundle:Blog:deletePost }
blog_update:
    path:     /update/{id}
    defaults: { _controller: BlogBundle:Blog:update }
blog_showDetail:
    path:     /Detail/{id}
    defaults: { _controller: BlogBundle:Blog:showDetail }
blog_showCmt:
    path:     /Detail/{id}
    defaults: { _controller: BlogBundle:Blog:showCt }
blog_createComments:
    path:     /createC
    defaults: { _controller: BlogBundle:Blog:createC }
blog_deleteC:
    path:     /deleteC/{id}
    defaults: { _controller: BlogBundle:Blog:deleteCmt }
blog_updateC:
    path:     /updateC/{id}
    defaults: { _controller: BlogBundle:Blog:updateC}
blog_LikeP:
    path:     /showl/{id}
    defaults: { _controller: BlogBundle:Blog:like }
mobile_showp:
    path:     /showpm
    defaults: { _controller: BlogBundle:Blog:ShowPM }
mobile_addp:
    path:     /addpm
    defaults: { _controller: BlogBundle:Blog:AddPM }
mobile_deletep:
    path:     /deletepm
    defaults: { _controller: BlogBundle:Blog:deletePM }
mobile_editp:
    path:     /editpm
    defaults: { _controller: BlogBundle:Blog:EditPM }
mobile_views:
    path:     /viewspm
    defaults: { _controller: BlogBundle:Blog:ViewsPM }
mobile_likepm:
    path:     /likepm
    defaults: { _controller: BlogBundle:Blog:LikePM }
mobile_showdpm:
    path:     /showdpm
    defaults: { _controller: BlogBundle:Blog:ShowDPM }
mobile_showcm:
    path:     /showcm
    defaults: { _controller: BlogBundle:Blog:ShowCM }
mobile_addc:
    path:     /addcm
    defaults: { _controller: BlogBundle:Blog:AddCM }
mobile_deletec:
    path:     /deletecm
    defaults: { _controller: BlogBundle:Blog:deleteCM }
mobile_cheklike:
        path:  /check
        defaults: { _controller: BlogBundle:Blog:CheckLikePM }
mobile_getlikes:
    path:     /getlikes
    defaults: { _controller: BlogBundle:Blog:getLikePM }
mobile_getnbc:
    path:     /getnbc
    defaults: { _controller: BlogBundle:Blog:getNbcPM }
mobile_editc:
    path:     /editcm
    defaults: { _controller: BlogBundle:Blog:EditCM }

